version: '3.9'
services:
  api:
    # restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: api/.env
    environment:
      - DB_HOST=db
    volumes:
      - ./api/:/usr/src/api
    ports:
      - "172.17.0.1:3000:3000"
    depends_on:
      - db

  adminer:
    image: adminer
    # restart: always
    ports:
      - "172.17.0.1:8080:8080"

  db:
    image: postgres:13-alpine
    # restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: api/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT}
    ports:
      - "172.17.0.1:5432:5432"
    healthcheck:
      test: [ "CMD", "postgresDB", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

volumes:
  db_data: {}
