version: '3.9'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: api/.env
    environment:
      - DB_HOST=db
    volumes:
      - ./api/:/usr/src/api
    ports:
      - "3000:3000"
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-db_zwo}
      POSTGRES_PASSWORD: ${DB_PASS:-db_zwo}
      POSTGRES_DB: ${DB_NAME_DEVELOPMENT:-db_zwo}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "postgresDB", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

volumes:
  db_data: {}
