name: build and test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create an .env file
        run: cp ./api/.env.sample ./api/.env

      - name: Run App
        run: make start

      - name: Run lint checks
        run: make node c="npm run lint:check"

      - name: Run Tests
        run: make node c="npm run test"
